# File: /Users/zhangjiahao/IdeaProjects/swarm/backend/workers/user/wrangler.toml
name = "swarm-user"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "swarm-db"
database_id = "4f360bda-ea4b-4fde-b3a0-d759f4180295"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = "swarm"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "ac5430ca9d234186862f6b4300d50b5a" # 对应 CACHE_KV 空间的 id 字段

[vars]
WX_APP_ID = "wxdebda985cf78a90d"
ALLOWED_ORIGIN = "*"
